version: '3.8'

services:
  java-server:
    build: .
    container_name: java-server-container
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m
    env_file:
      - WebContent/WEB-INF/.env  # .envファイルのパスを指定
    command: ["java", "-cp", "WebContent/WEB-INF/lib/*:bin", "server.AppServer", "8080", "/", "WebContent"]
